input_size: 64
output_size: 256
scale_factor: 4

pre_upsample: false
conv1_size: 5
conv1_num: 256
conv2_size: 3
conv2_num: 64

max_epoch: 400
batch_size: 64
learning_rate: 0.001
loss_fn: "MSE"

use_pretrained: false
pretrained_path: ""
use_checkpoint: false
checkpoint_path: "checkpoint/ESPCN.pth"
