input_size: 64
output_size: 256
scale_factor: 4

pre_upsample: false
d: 128
s: 32
m: 4

max_epoch: 400
batch_size: 64
learning_rate: 0.0001
loss_fn: "MSE"

use_pretrained: false
pretrained_path: ""
use_checkpoint: true
checkpoint_path: "checkpoint/FSRCNN.pth"

