input_size: 64
output_size: 256

pre_upsample: true
conv1_kernel_size: 9
conv1_kernel_num: 128
conv2_kernel_size: 5
conv2_kernel_num: 64
conv3_kernel_size: 5

max_epoch: 100
batch_size: 16
learning_rate: 0.001
loss_fn: "MSE"

use_pretrained: false
pretrained_path: ""
use_checkpoint: false
checkpoint_path: "checkpoint/SRCNN.pth"

